// Code generated by goadlc v3 - DO NOT EDIT.
package b

import ()

type B struct {
	A string `json:"a"`
}

func New_B(
	a string,
) B {
	return B{
		A: a,
	}
}

func Make_B(
	a string,
) B {
	ret := B{
		A: a,
	}
	return ret
}
