// Code generated by goadlc v3 - DO NOT EDIT.
package b

import ()

type B struct {
	_B
}

type _B struct {
	A string `json:"a"`
}

func MakeAll_B(
	a string,
) B {
	return B{
		_B{
			A: a,
		},
	}
}

func Make_B(
	a string,
) B {
	ret := B{
		_B{
			A: a,
		},
	}
	return ret
}
