// Code generated by goadlc v3 - DO NOT EDIT.
package struct_with_void

import ()

type StructB[X any] struct {
	B struct{} `json:"B"`
}

func New_StructB[X any](
	b struct{},
) StructB[X] {
	return StructB[X]{
		B: b,
	}
}

func Make_StructB[X any](
	b struct{},
) StructB[X] {
	ret := StructB[X]{
		B: b,
	}
	return ret
}

type StructC = StructOf

type StructOf struct {
	A struct{} `json:"A"`
}

func New_StructOf(
	a struct{},
) StructOf {
	return StructOf{
		A: a,
	}
}

func Make_StructOf(
	a struct{},
) StructOf {
	ret := StructOf{
		A: a,
	}
	return ret
}
