// Code generated by goadlc v3 - DO NOT EDIT.
package struct_of_structs_with_defaults

import (
	goadl "github.com/adl-lang/goadl_rt/v3"
	"github.com/adl-lang/goadl_rt/v3/customtypes"
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
	"github.com/adl-lang/goadl_rt/v3/sys/types"
)

func Texpr_Bar() adlast.ATypeExpr[Bar] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "Bar"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[Bar](te)
}

func AST_Bar() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"Bar",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"d",
						"d",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_just[any](
							"doe a deer",
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"svb",
						"svb",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"StringMap",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_primitive(
										"Vector",
									),
									[]adlast.TypeExpr{
										adlast.MakeAll_TypeExpr(
											adlast.Make_TypeRef_primitive(
												"Bool",
											),
											[]adlast.TypeExpr{},
										),
									},
								),
							},
						),
						types.Make_Maybe_just[any](
							map[string]interface{}{"a": []interface{}{true, false}, "b": []interface{}{false, true}},
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("exer04.struct_of_structs_with_defaults", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "Bar"),
		AST_Bar(),
	)
}

func Texpr_Fizz() adlast.ATypeExpr[Fizz] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "Fizz"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[Fizz](te)
}

func AST_Fizz() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"Fizz",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"A",
						"A",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"exer04.struct_of_structs_with_defaults",
									"Foo",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"B",
						"B",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"exer04.struct_of_structs_with_defaults",
									"Bar",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("exer04.struct_of_structs_with_defaults", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "Fizz"),
		AST_Fizz(),
	)
}

func Texpr_Foo() adlast.ATypeExpr[Foo] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "Foo"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[Foo](te)
}

func AST_Foo() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"Foo",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"d",
						"d",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Int32",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_just[any](
							1,
						),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("exer04.struct_of_structs_with_defaults", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "Foo"),
		AST_Foo(),
	)
}

func Texpr_NT() adlast.ATypeExpr[NT] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "NT"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[NT](te)
}

func AST_NT() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"NT",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_newtype_(
			adlast.MakeAll_NewType(
				[]adlast.Ident{},
				adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"exer04.struct_of_structs_with_defaults",
							"StructOfStruct",
						),
					),
					[]adlast.TypeExpr{},
				),
				types.Make_Maybe_nothing[any](),
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("exer04.struct_of_structs_with_defaults", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "NT"),
		AST_NT(),
	)
}

func Texpr_StructOfStruct() adlast.ATypeExpr[StructOfStruct] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "StructOfStruct"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[StructOfStruct](te)
}

func AST_StructOfStruct() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"StructOfStruct",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"A",
						"A",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"exer04.struct_of_structs_with_defaults",
									"Foo",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"B",
						"B",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"exer04.struct_of_structs_with_defaults",
									"Bar",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"c",
						"c",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"exer04.struct_of_structs_with_defaults",
									"Fizz",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("exer04.struct_of_structs_with_defaults", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("exer04.struct_of_structs_with_defaults", "StructOfStruct"),
		AST_StructOfStruct(),
	)
}
