// Code generated by goadlc v3 - DO NOT EDIT.
package b

import ()

type B struct {
	A string `json:"a"`
	B string `json:"b"`
}

func New_B(
	a string,
	b string,
) B {
	return B{
		A: a,
		B: b,
	}
}

func Make_B(
	a string,
	b string,
) B {
	ret := B{
		A: a,
		B: b,
	}
	return ret
}
