// Code generated by goadlc v3 - DO NOT EDIT.
package struct_of_structs

import ()

type Bar struct {
	_Bar
}

type _Bar struct {
	D string `json:"d"`
}

func MakeAll_Bar(
	d string,
) Bar {
	return Bar{
		_Bar{
			D: d,
		},
	}
}

func Make_Bar(
	d string,
) Bar {
	ret := Bar{
		_Bar{
			D: d,
		},
	}
	return ret
}

type Fizz struct {
	_Fizz
}

type _Fizz struct {
	A Foo   `json:"A"`
	B Bar   `json:"B"`
	C *Fizz `json:"c"`
}

func MakeAll_Fizz(
	a Foo,
	b Bar,
	c *Fizz,
) Fizz {
	return Fizz{
		_Fizz{
			A: a,
			B: b,
			C: c,
		},
	}
}

func Make_Fizz(
	a Foo,
	b Bar,
	c *Fizz,
) Fizz {
	ret := Fizz{
		_Fizz{
			A: a,
			B: b,
			C: c,
		},
	}
	return ret
}

type Foo struct {
	_Foo
}

type _Foo struct {
	D int32 `json:"d"`
}

func MakeAll_Foo(
	d int32,
) Foo {
	return Foo{
		_Foo{
			D: d,
		},
	}
}

func Make_Foo(
	d int32,
) Foo {
	ret := Foo{
		_Foo{
			D: d,
		},
	}
	return ret
}

type StructOfStruct struct {
	_StructOfStruct
}

type _StructOfStruct struct {
	A Foo  `json:"A"`
	B Bar  `json:"B"`
	C Fizz `json:"c"`
}

func MakeAll_StructOfStruct(
	a Foo,
	b Bar,
	c Fizz,
) StructOfStruct {
	return StructOfStruct{
		_StructOfStruct{
			A: a,
			B: b,
			C: c,
		},
	}
}

func Make_StructOfStruct(
	a Foo,
	b Bar,
	c Fizz,
) StructOfStruct {
	ret := StructOfStruct{
		_StructOfStruct{
			A: a,
			B: b,
			C: c,
		},
	}
	return ret
}
