// Code generated by goadlc v3 - DO NOT EDIT.
package ast

import (
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
)

type X struct {
	Ast map[string]adlast.Module `json:"ast"`
}

func New_X(
	ast map[string]adlast.Module,
) X {
	return X{
		Ast: ast,
	}
}

func Make_X(
	ast map[string]adlast.Module,
) X {
	ret := X{
		Ast: ast,
	}
	return ret
}
