// Code generated by goadlc v3 - DO NOT EDIT.
package ast

import (
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
)

type X struct {
	_X
}

type _X struct {
	Ast map[string]adlast.Module `json:"ast"`
}

func MakeAll_X(
	ast map[string]adlast.Module,
) X {
	return X{
		_X{
			Ast: ast,
		},
	}
}

func Make_X(
	ast map[string]adlast.Module,
) X {
	ret := X{
		_X{
			Ast: ast,
		},
	}
	return ret
}
