// Code generated by goadlc v3 - DO NOT EDIT.
package ast

import (
	goadl "github.com/adl-lang/goadl_rt/v3"
	"github.com/adl-lang/goadl_rt/v3/customtypes"
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
	"github.com/adl-lang/goadl_rt/v3/sys/types"
)

func Texpr_X() adlast.ATypeExpr[X] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("exer05.ast", "X"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[X](te)
}

func AST_X() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"X",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"ast",
						"ast",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"StringMap",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"sys.adlast",
											"Module",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("exer05.ast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("exer05.ast", "X"),
		AST_X(),
	)
}
